apiVersion: v1
kind: Pod
metadata:
  name: grafana
  labels:
    name: grafana
spec:
  containers:
  - name: grafana
    image: docker.io/grafana/grafana
    ports:
    - containerPort: 80
    volumeMounts:
    - name: grafana-source
      mountPath: /etc/grafana/provisioning/datasources
  volumes:
    - name: grafana-source
      configMap:
        name: grafana-source
