bases:
- ../bases
secretGenerator:
- name: loki-objectstorage
  namespace: <namespace>
  literals:
  - endpoint=http://minio:minio123@minio.observatorium-minio.svc.cluster.local.:9000/loki
- name: thanos-objectstorage
  namespace: <namespace>
  files:
  - thanos.yaml=thanos.generated.yaml
- name: observatorium-xyz-tls
  namespace: <namespace>
  files:
  - cert.pem=tls.generated.crt
  - key.pem=tls.generated.key
configMapGenerator:
- name: observatorium-xyz-tls
  namespace: <namespace>
  files:
  - ca.pem=rootCA.generated.crt
generatorOptions:
  disableNameSuffixHash: true