apiVersion: v1
kind: Service
metadata:
  name: thanos-store
spec:
  selector:
    name: thanos-store
  ports:
    - protocol: TCP
      port: 10902
      targetPort: 10902
      name: http
    - protocol: TCP
      port: 10901
      targetPort: 10901
      name: grpc