"roleBindings":
- "name": "test-read"
  "roles":
  - "read"
  "subjects":
  - "kind": "user"
    "name": "read.monitoring.test"
- "name": "test-write"
  "roles":
  - "write"
  "subjects":
  - "kind": "user"
    "name": "write.monitoring.test"

"roles":
- "name": "read"
  "permissions":
  - "read"
  "resources":
  - "logs"
  - "metrics"
  "tenants":
  - "test"
- "name": "write"
  "permissions":
  - "write"
  "resources":
  - "logs"
  - "metrics"
  "tenants":
  - "test"
