apiVersion: v1
kind: Pod
metadata:
  name: prometheus-mtls
spec:
  containers:
  - name: prometheus-mtls
    args:
      - --config.file=/etc/prometheus/prometheus.yaml
    image: quay.io/prometheus/prometheus
    ports:
    - containerPort: 80
    volumeMounts:
    - name: prom-mtls
      mountPath: /etc/prometheus/certs
    - name: prom-config
      mountPath: /etc/prometheus
  volumes:
    - name: prom-mtls
      configMap:
        name: prom-mtls
    - name: prom-config
      configMap:
        name: prom-config