apiVersion: core.observatorium.io/v1alpha1
kind: Observatorium
metadata:
  name: observatorium-xyz
  namespace: observatorium
  labels:
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-cr
    app.kubernetes.io/part-of: observatorium
spec:
  store:
    cache:
      exporterImage: 'prom/memcached-exporter:v0.6.0'
      exporterVersion: v0.6.0
      image: 'docker.io/memcached:1.6.3-alpine'
      memoryLimitMb: 1024
      replicas: 1
      version: 1.6.3-alpine
    image: quay.io/thanos/thanos:v0.24.0
    shards: 1
    version: v0.24.0
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  loki:
    image: docker.io/grafana/loki:2.2.0
    replicas:
      compactor: 1
      distributor: 1
      ingester: 1
      querier: 1
      query_frontend: 1
      table_manager: 1
    version: 2.1.0
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1G
  compact:
    enableDownsampling: false
    image: quay.io/thanos/thanos:v0.24.0
    replicas: 1
    retentionResolution1h: 1s
    retentionResolution5m: 1s
    retentionResolutionRaw: 14d
    version: v0.24.0
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  receivers:
    image: quay.io/thanos/thanos:v0.24.0
    replicas: 1
    version: v0.24.0
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  query:
    image: quay.io/thanos/thanos:v0.24.0
    replicas: 1
    version: v0.24.0
  apiQuery:
    image: quay.io/thanos/thanos:v0.24.0
    version: v0.24.0
  hashrings:
    - hashring: default
      tenants: []
  thanosReceiveController:
    image: quay.io/observatorium/thanos-receive-controller:master-2021-04-28-ee165b6
    version: master-2021-04-28-ee165b6
  api:
    image: quay.io/observatorium/api:main-2022-03-03-v0.1.2-139-gb3a1918
    rbac:
      roleBindings:
        - name: test
          roles:
            - read-write
          subjects:
            - kind: user
              name: admin@example.com
      roles:
        - name: read-write
          permissions:
            - read
            - write
          resources:
            - logs
            - metrics
          tenants:
            - test
    replicas: 1
    tenants:
      # - id: 1610b0c3-c509-4592-a256-a1871353dbfa
      #   name: test
      #   oidc:
      #     clientID: test
      #     clientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
      #     issuerCAPath: /var/run/tls/ca.pem
      #     issuerURL: 'https://<dex_issuer_url>/dex'
      #     usernameClaim: email
      - id: 1610b0c3-c509-4592-a256-a1871353dbfa
        name: test
        mTLS:
          caKey: ca.pem
          configMapName: observatorium-xyz-mtls
    tls:
      caKey: ca.pem
      certKey: cert.pem
      configMapName: observatorium-xyz-tls
      keyKey: key.pem
      secretName: observatorium-xyz-tls
    version: main-2022-03-03-v0.1.2-139-gb3a1918
  queryFrontend:
    image: quay.io/thanos/thanos:v0.24.0
    replicas: 1
    version: v0.24.0
  rule:
    image: quay.io/thanos/thanos:v0.24.0
    replicas: 1
    version: v0.24.0
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  securityContext: {}
  objectStorageConfig:
    loki:
      accessKeyIdKey: aws_access_key_id
      bucketsKey: buckets
      endpointKey: endpoint
      regionKey: region
      secretAccessKeyKey: aws_secret_access_key
      secretName: loki-objectstorage
    thanos:
      key: thanos.yaml
      name: thanos-objectstorage