apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: test
    app.kubernetes.io/instance: e2e-test
    app.kubernetes.io/name: observatorium-up
    app.kubernetes.io/version: master-2020-06-03-8a20b4e
  name: observatorium-up-metrics-mtls
  namespace: <namespace>
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/component: test
        app.kubernetes.io/instance: e2e-test
        app.kubernetes.io/name: observatorium-up
        app.kubernetes.io/version: master-2020-06-03-8a20b4e
    spec:
      containers:
      - args:
        - --endpoint-type=metrics
        - --endpoint-write=https://observatorium-xyz-observatorium-api.observatorium.svc.cluster.local:8080/api/metrics/v1/test/api/v1/receive
        - --endpoint-read=https://observatorium-xyz-observatorium-api.observatorium.svc.cluster.local:8080/api/metrics/v1/test/api/v1/query
        - --period=1s
        - --duration=2m
        - --name=foo
        - --labels=bar="baz"
        - --latency=10s
        - --initial-query-delay=5s
        - --threshold=0.90
        - --tls-ca-file=/mnt/tls/ca.pem
        - --tls-client-cert-file=/mnt/tls/client-cert.crt
        - --tls-client-private-key-file=/mnt/tls/client-key.key
        image: quay.io/observatorium/up:master-2020-06-03-8a20b4e
        name: observatorium-up
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - mountPath: /mnt/tls
          name: tls
          readOnly: true
        - mountPath: /var/shared
          name: shared
          readOnly: true
      initContainers: []
      restartPolicy: OnFailure
      volumes:
      - configMap:
          name: observatorium-xyz-tls
        name: tls
      - emptyDir: {}
        name: shared
      - configMap:
          name: observatorium-xyz-tls
        name: oidc-tls