# Create a kustomization.yaml file with ConfigMapGenerator
configMapGenerator:
- name: prom-mtls
  namespace: monitoring
  files:
  - rootCA.pem=certs/rootCA.generated.crt
  - client.pem=certs/client-tls.generated.crt
  - client.key=certs/client-tls.generated.key
- name: prom-config
  namespace: monitoring
  files:
  - prometheus.yaml=prometheus/prometheus.yaml
- name: obs-certs
  namespace: monitoring
  files:
  - ca.pem=certs/rootCA.generated.crt
  - tls.pem=certs/server-tls.generated.crt
  - tls.key=certs/server-tls.generated.key
- name: tenants
  namespace: monitoring
  files:
  - tenants.yaml=observatorium/tenants.yaml
  - rbac.yaml=observatorium/rbac.yaml
resources:
- base/namespace.yaml
- prometheus/prom-pod.yaml
- prometheus/prom-svc.yaml
- prometheus/prom-route.yaml
- metricgen/metricgen-svc.yaml
- metricgen/metricgen.yaml
- observatorium/obs-svc.yaml
- observatorium/obs-route.yaml
- observatorium/obs-pod.yaml
generatorOptions:
  disableNameSuffixHash: true