# Create a kustomization.yaml file with ConfigMapGenerator
configMapGenerator:
- name: prom-mtls
  namespace: monitoring
  files:
  - rootCA.pem=config/certs/rootCA.generated.crt
  - client.pem=config/certs/client-tls.generated.crt
  - client.key=config/certs/client-tls.generated.key
- name: prom-config
  namespace: monitoring
  files:
  - prometheus.yaml=config/prometheus.yaml
- name: obs-certs
  namespace: monitoring
  files:
  - ca.pem=config/certs/rootCA.generated.crt
  - tls.pem=config/certs/server-tls.generated.crt
  - tls.key=config/certs/server-tls.generated.key
- name: tenants
  namespace: monitoring
  files:
  - tenants.yaml=config/tenants.yaml
  - rbac.yaml=config/rbac.yaml
- name: thanos-store
  namespace: monitoring
  files:
  - bucket.yaml=config/bucket.yaml
- name: grafana-source
  namespace: monitoring
  files:
  - datasource.yaml=config/datasource.generated.yaml
resources:
- namespace/namespace.yaml
generatorOptions:
  disableNameSuffixHash: true