apiVersion: v1
kind: Service
metadata:
  name: thanos-receive
spec:
  selector:
    name: thanos-receive
  ports:
    - protocol: TCP
      port: 19291
      targetPort: 19291
      name: remote-write
    - protocol: TCP
      port: 10901
      targetPort: 10901
      name: grpc