"enablePasswordDB": true
"issuer": "<dex_issuer_url>"
"logger":
  "level": "debug"
"oauth2":
  "passwordConnector": "local"
"staticClients":
- "id": "test"
  "issuerCAPath": "/var/run/tls/ca.pem"
  "name": "test"
  "secret": "<dex_tenant_client_secret>"
"staticPasswords":
- "email": "admin@example.com"
  "hash": <dex_admin_pass_hash>
  "userID": "08a8684b-db88-4b73-90a9-3cd1661f5466"
  "username": "admin"
"storage":
  "config":
    "file": "/storage/dex.db"
  "type": "sqlite3"
"web":
  "https": "0.0.0.0:5556"
  "tlsCert": "/etc/dex/tls/tls.crt"
  "tlsKey": "/etc/dex/tls/tls.key"
"expiry":
  "deviceRequests": "8760h"
  "signingKeys": "8760h"
  "idTokens": "8760h"