"enablePasswordDB": true
"issuer": "https://dex.dex.svc.cluster.local:5556/dex"
"logger":
  "level": "debug"
"oauth2":
  "passwordConnector": "local"
"staticClients":
- "id": "test"
  "issuerCAPath": "/var/run/tls/ca.pem"
  "name": "test"
  "secret": "ZXhhbXBsZS1hcHAtc2VjcmV0"
"staticPasswords":
- "email": "admin@example.com"
  "hash": "$2a$10$ugng/2zzuraMTOQl2Kibve0invnP1nP5fMA5AgE8AOLtiHuNRiYrq"
  "userID": "08a8684b-db88-4b73-90a9-3cd1661f5466"
  "username": "admin"
"storage":
  "config":
    "file": "/storage/dex.db"
  "type": "sqlite3"
"web":
  "https": "0.0.0.0:5556"
  "tlsCert": "/etc/dex/tls/tls.crt"
  "tlsKey": "/etc/dex/tls/tls.key"
"expiry":
  "deviceRequests": "8760h"
  "signingKeys": "8760h"
  "idTokens": "8760h"