bases:
- ../bases
secretGenerator:
- name: dex
  namespace: <namespace>
  files:
  - config.yaml=config.generated.yaml
- name: dex-tls
  namespace: <namespace>
  files:
  - tls.crt=tls.generated.crt
  - tls.key=tls.generated.key
generatorOptions:
  disableNameSuffixHash: true