apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: observatorium
spec:
  to:
    kind: Service
    name: observatorium-svc
  port:
    targetPort: 8080
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None