apiVersion: v1
kind: Pod
metadata:
  name: thanos-query
  labels:
    name: thanos-query
spec:
  containers:
  - name: thanos-query
    args:
    - query
    - --http-address=0.0.0.0:9090
    - --log.level=debug
    - --query.timeout=15m
    - --query.auto-downsampling
    - --store=thanos-receive.monitoring.svc.cluster.local:10901
    - --store=thanos-store.monitoring.svc.cluster.local:10901
    image: quay.io/thanos/thanos:v0.22.0
    ports:
    - containerPort: 80